version: '3.9'

services:
  inventory-service:
    image: inventoryservice
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=InventoryDb;Username=postgres;Password=Postgres123
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: InventoryDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: